### ISSUE TITLE
New path to CHECKLIST (via input-file) not working

### ISSUE THREAD

**Issue by rknj** [wyozi/contextual-qa-checklist-action#22]
Setting the path to the CHECKLIST file does not work or I do not use `input-file` in the right way.
I'm getting this outcome:

```
> Run wyozi/contextual-qa-checklist-action@master
  with:
    gh-token: ***
    input-file: .github/CHECKLIST.yml
    comment-header: Great PR! Please pay attention to the following items before merging:
    comment-footer: This is an automatically generated QA checklist based on modified files
    include-hidden-files: false
    show-paths: true
Error: ENOENT: no such file or directory, open '.github/CHECKLIST.yml'
```
And yes, I created the file at the right place: `sandbox/.github/CHECKLIST.yml` (sandbox being the repo name)

**Comment by wyozi** [comment]
And just to verify, your action includes a `actions/checkout` step before  `contextual-qa-checklist-action`, right? 😁

**Comment by rknj** [comment]
Yes ;-)  
`Download action repository 'wyozi/contextual-qa-checklist-action@master' (SHA:c063201bfa7fe8e9f72fb70ed2fe8cc0718c34c6)`

I tried to move CHECKLIST.yml at the root level and now I get this error:
`Error: ENOENT: no such file or directory, open 'CHECKLIST.yml'`

**Comment by rknj** [comment]
I've reorganize my workflow and now it's OK.

Which is not clear is that I got this `Download action repository 'wyozi/contextual-qa-checklist-action@master' (SHA:c063201bfa7fe8e9f72fb70ed2fe8cc0718c34c6)` before getting the error I shared
